### ISSUE TITLE
BBOX subset unhashable type dict

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/cjio#11]
```
$ cjio /data/citymodels/Zurich/Building_LoD2_V10.json subset --bbox 2681133 1246440 2682862 1247462 save example_data/zurich_subset.json
Parsing /data/citymodels/Zurich/Building_LoD2_V10.json
Subset of CityJSON
Traceback (most recent call last):
  File "/home/balazs/.local/share/virtualenvs/cjio-xu4bWm9P/bin/cjio", line 11, in <module>
    load_entry_point('cjio', 'console_scripts', 'cjio')()
  File "/home/balazs/.local/share/virtualenvs/cjio-xu4bWm9P/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/balazs/.local/share/virtualenvs/cjio-xu4bWm9P/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/balazs/.local/share/virtualenvs/cjio-xu4bWm9P/lib/python3.6/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/balazs/.local/share/virtualenvs/cjio-xu4bWm9P/lib/python3.6/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/home/balazs/.local/share/virtualenvs/cjio-xu4bWm9P/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/balazs/Development/cjio/cjio/cjio.py", line 92, in process_pipeline
    cm = processor(cm)
  File "/home/balazs/Development/cjio/cjio/cjio.py", line 468, in processor
    s = s.get_subset_bbox(bbox, exclude=exclude)
  File "/home/balazs/Development/cjio/cjio/cityjson.py", line 606, in get_subset_bbox
    re.add(self.j['CityObjects'][each])
TypeError: unhashable type: 'dict'
```

**Comment by Merichbier** [comment]
Ran into the same bug =( Any update on this ?

**Comment by balazsdukai** [comment]
Not yet.

**Comment by hugoledoux** [comment]
I fixed it, I think. At least now it works for me with that exact query and I tried 2-3 more files, should be fine now.

e17e66d7ea1669172d2357d03991e9934d39dcf8
