### ISSUE TITLE
Python module 'mapbox_earcut' missing

### ISSUE THREAD

**Issue by cfrank0214** [tudelft3d/cjio#23]
I've installed via 'pip3 cjio'

cjio test.json export test.obj
Parsing test.json
OBJ export skipped: Python module 'mapbox_earcut' missing (to triangulate faces)
Install it: https://github.com/skogler/mapbox_earcut_python

Might be related to this error as well. 

cjio test.json remove_textures export test.obj
Parsing test.json
Remove all textures
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/cjio", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cjio/cjio.py", line 96, in process_pipeline
    cm = processor(cm)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cjio/cjio.py", line 406, in processor
    cm.remove_textures()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cjio/cityjson.py", line 839, in remove_textures
    if self.j["appearance"] is None or len(self.j["appearance"]) == 0:
KeyError: 'appearance'

**Comment by balazsdukai** [comment]
Hi,
please do as it says in the traceback:
```
OBJ export skipped: Python module 'mapbox_earcut' missing (to triangulate faces)
Install it: https://github.com/skogler/mapbox_earcut_python
```

**Comment by cfrank0214** [comment]
Thanks @balazsdukai !!!

Is there a reason that Mapbox Earcut is not included. The install instructions in the Skogler github repo are limited. 

Why not just add it to install_requires within your setup.py? That's what I did after cloning your repo.

**Comment by balazsdukai** [comment]
That's because the earcut library is only needed for a few export formats like obj, glb and it is not required for the main operation of cjio.
